### ISSUE TITLE
Upload v0.6 to pypi?

### ISSUE THREAD

**Issue by RobbieClarken** [paulscherrerinstitute/pcaspy#20]
It's been a while since I last used pcaspy - great to see it's still being developed!

The latest version on PyPI is 0.5.1. Would it be possible to upload a 0.6 release?

**Comment by xiaoqiangwang** [comment]
Yes. I thought I could make the release 0.6 last year.  

The Issue 13 is specially hard to tackle. And I was later distracted by other things and hadn't come back to it. I hope to find time again in June.

**Comment by xiaoqiangwang** [comment]
0.6.0  released on June 6, 2016.
