### ISSUE TITLE
Printing Alarm and Severity on every setParam call

### ISSUE THREAD

**Issue by MikeHart85** [paulscherrerinstitute/pcaspy#21]
Commit d7dbd89 introduced the following two unconditional `print` statements at the top of `Driver.setParamStatus`:

```python
    def setParamStatus(self, reason, alarm=None, severity=None):
        """[...]"""
        print "alarm", self.pvDB[reason].alarm, alarm
        print "severity", self.pvDB[reason].severity, severity
```

These messages are also output every time you call `Driver.setParam`, since that calls `setParamStatus`. 

If `setParam` is called often, as it is in our case, this causes quite a lot of unwanted spam to stdout.

Could these two lines please be removed?

**Comment by xiaoqiangwang** [comment]
I removed this debug output in commit #f74a052
