### ISSUE TITLE
Environment variables not found when installing with pip

### ISSUE THREAD

**Issue by dmichel76** [paulscherrerinstitute/pcaspy#27]
Hi,

I've just tried installing from pip on my ubuntu machine but, although both environment variables EPICS_BASE and EPICS_HOST_ARCH are set (in my .bashrc file), the setup.py install script cannot see them.

Doing a os.environ.get("EPICS_BASE") directly on the python console results in the correct path being returned.

Any thoughts?

**Comment by dmichel76** [comment]
Nevermind, it seems to work fine

**Comment by xiaoqiangwang** [comment]
I intended to suggest the -E flag, but then I saw you said the problem is solved by itself...
Anyway whether the environment variables should be kept is set in ``/etc/sudoers``.
https://help.ubuntu.com/community/Sudoers
The setting is either _env_reset_ or _env_keep_.
