### ISSUE TITLE
pcaspy 0.6.2 Broken with python 3.5.2 

### ISSUE THREAD

**Issue by protofabrik** [paulscherrerinstitute/pcaspy#30]
It seems that the package is broken with python 3.5.2, I'm not 100% sure but the problem might also be in Swig

..
```
In [1]: import pcaspy

In [2]: pcaspy.SimpleServer()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/lib/python3.5/site-packages/pcaspy/cas.py in __init__(self)
    490         try:
--> 491             self.this.append(this)
    492         except builtins.Exception:

/usr/lib/python3.5/site-packages/pcaspy/cas.py in <lambda>(self, name)
    480     __swig_getmethods__ = {}
--> 481     __getattr__ = lambda self, name: _swig_getattr(self, caServer, name)
    482     __repr__ = _swig_repr

/usr/lib/python3.5/site-packages/pcaspy/cas.py in _swig_getattr(self, class_type, name)
     83         return method(self)
---> 84     raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
     85 

AttributeError: 'caServer' object has no attribute 'this'

During handling of the above exception, another exception occurred:

NameError                                 Traceback (most recent call last)
<ipython-input-2-038db7c60615> in <module>()
----> 1 pcaspy.SimpleServer()

/usr/lib/python3.5/site-packages/pcaspy/driver.py in __init__(self)
    615     """
    616     def __init__(self):
--> 617         cas.caServer.__init__(self)
    618 
    619     def __del__(self):

/usr/lib/python3.5/site-packages/pcaspy/cas.py in __init__(self)
    490         try:
    491             self.this.append(this)
--> 492         except builtins.Exception:
    493             self.this = this
    494     __swig_destroy__ = _cas.delete_caServer

NameError: name 'builtins' is not defined

```

**Comment by xiaoqiangwang** [comment]
We have 0.6.2 for Anaconda Python 3.5.1, and that works. I need to try with Python 3.5.2. What is the SWIG version?

**Comment by protofabrik** [comment]
As far as I know latest stable (system is running on arch): 

```
 swig -version

SWIG Version 3.0.10

Compiled with g++ [x86_64-pc-linux-gnu]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information

```

**Comment by protofabrik** [comment]
Quick and dirty hack to make it work is to add `import builtins` to the generated cas.py . 

For some reason it does this, which screws up the import 
```
try:
    import builtins as __builtin__
except ImportError:
    import builtins
```

No idea, why this is needed...

**Comment by xiaoqiangwang** [comment]
I tried with Python 3.5.2 and SWIG 3.0.10, and saw the same error as your first post. Then I downgrade SWIG to 3.0.8, it works again.

**Comment by xiaoqiangwang** [comment]
The conflict change of SWIG seems to be related to this PR
https://github.com/swig/swig/pull/584

**Comment by xiaoqiangwang** [comment]
This problem is a bit twisting. In python 3, there is no more "__builtin__" module name, but SWIG creates compatible code `` import builtins as __builtin__``. At this point it works. But the 2to3 conversion used in _setup.py_ will again convert appearance of  ``__builtin__`` to ``builtins``. Then it breaks.

Initially 2to3 helps to quickly support Python3. Now it maybe a good chance to make a proper Python3 support. Commit df7d463 gets rid of 2to3 conversion. The changes are mostly trivial. Only to get compatible metaclass definition, an additional class ``DriverBase`` has to be introduced.

**Comment by xiaoqiangwang** [comment]
0.6.3 is released with this bug fixed.
