### ISSUE TITLE
Import Error on macOS when using pcaspy installed from pip.

### ISSUE THREAD

**Issue by mattgibbs** [paulscherrerinstitute/pcaspy#34]
I just upgraded pcaspy to the latest release through pip: 
`$ pip install --upgrade pcaspy`
but now when I try to use it, I get the following error:

> Traceback (most recent call last):
  File "testing-ioc.py", line 5, in <module>
    from pcaspy import Driver, SimpleServer
  File "/usr/local/lib/python2.7/site-packages/pcaspy/__init__.py", line 1, in <module>
    from driver import Driver, SimpleServer, PVInfo, SimplePV
  File "/usr/local/lib/python2.7/site-packages/pcaspy/driver.py", line 1, in <module>
    import cas
  File "/usr/local/lib/python2.7/site-packages/pcaspy/cas.py", line 28, in <module>
    _cas = swig_import_helper()
  File "/usr/local/lib/python2.7/site-packages/pcaspy/cas.py", line 24, in swig_import_helper
    _mod = imp.load_module('_cas', fp, pathname, description)
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/pcaspy/_cas.so, 2): Library not loaded: /Users/wang/epics/base-3.14.12.5/lib/darwin-x86/libasIoc.3.14.12.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/pcaspy/_cas.so
  Reason: image not found

It looks like _cas.so is trying to find the EPICS libraries in '/Users/wang/epics/base-3.14.12.5', rather than wherever $EPICS_BASE is.  If I download the source tarball, and do:
`$ python setup.py build`
`$ python setup.py install`
everything works fine, so it must be an issue with getting a pre-built version from pip.

**Comment by xiaoqiangwang** [comment]
Thanks for spotting the bug. I always try to link EPICS libraries statically. But it looks I have used the wrong epics path. I will be more careful for the packaging.

**Comment by mattgibbs** [comment]
Thanks for all your work, Xiaoqiang!

**Comment by xiaoqiangwang** [comment]
0.6.3 is released to PyPI with EPICS base 3.14.12.6 builtin.
