### ISSUE TITLE
NameError: global name 'warnings' is not defined

### ISSUE THREAD

**Issue by MichaelRitzert** [paulscherrerinstitute/pcaspy#36]
Line 236 in pcaspy/gdd.i is
`warnings.warn("…")`
When this line is reached, warnings is undefined:
> Traceback (most recent call last):
>     File "/usr/lib64/python2.7/site-packages/pcaspy/driver.py", line 561, in getValue
>       value.put(newValue)
>     File "/usr/lib64/python2.7/site-packages/pcaspy/cas.py", line 290, in put
>       warnings.warn("gdd does not support data type %s. Conversion is involved." % value.dtype)
>  NameError: global name 'warnings' is not defined
>  Traceback (most recent call last):
>     File "/usr/lib64/python2.7/site-packages/pcaspy/cas.py", line 461, in read
>       def read(self, *args): return _cas.PV_read(self, *args)
>  RuntimeError: SWIG director method error. Exception Calling Python Code
>  filename="../../../../src/cas/generic/st/casStreamOS.cc" line number=478
>  Internal failure - unexpected problem with client's input - forcing disconnect
>

**Comment by xiaoqiangwang** [comment]
Thanks for spotting the bug. I added a test case for this.
