### ISSUE TITLE
Documentation on v.0.6.3 broken ?

### ISSUE THREAD

**Issue by xresende** [paulscherrerinstitute/pcaspy#37]
For the past few days we at the Brazilian Synchrotron Light Source have been trying to access the online documentation on version 0.6.3 but the section 'References' seems to be empty. We tried to compile the document (HTML and Latex) from the source code what the problem persists there.

Cheers!

**Comment by xiaoqiangwang** [comment]
Thanks for spotting the error! This error comes from the commit df7d463, which changed to use relative import inside the package. And the mock(1.x) module does not support. 

The fix commit 0b845ec is to use the built-in mock module for Python 3.3+. This also means the documents cannot be created using Python 2.7 - 3.2.

**Comment by xresende** [comment]
happy to help a project that is helping us!
