### ISSUE TITLE
Transfer long numpy arrays in a fast way?

### ISSUE THREAD

**Issue by piuupiuupiuu** [paulscherrerinstitute/pcaspy#42]
Hi,
currently I am trying to control a camera, which means that I also want to get the data. The data transfer of a numpy array is limited to 2047 elements, at least if my test was correct. I tried to get around this limit by splitting the data and send in multiple read requests. This works quite fine but it takes about 1.5 seconds for a picture of 493*659 pixels (about 160 arrays of 2047 elements).
Is there is smarter way to send this amount of data with EPICS? In EPICS 4 it seems to be possible to send bigger data packages, right? If its not possible I will do a workaround with a different network library until EPICS 4 is supported by pcaspy.

Thanks for your help!
Menno

**Comment by xiaoqiangwang** [comment]
Did you set the `EPICS_CA_MAX_ARRAY_BYTES` to some large value, e.g. 
``
export EPICS_CA_MAX_ARRAY_BYTES=50000000
``
This has to be set before starting the client and server.


I have an application transferring detector image of 1024x1024 without problems.

**Comment by piuupiuupiuu** [comment]
That works quite well! Thank you!
The only problem I ran into now is that `camonitor` in the **pyepics** lib seems to just quit working above some numpy array size bigger than 57600 and lower than 78400. Did you just not use `camonitor` (because in `pv.get()` its no problem) or do you use a different library at the client side?

I know this is not actually your problem, because its pyepics, but thanks for your help ;)

**Comment by xiaoqiangwang** [comment]
Right. I am not sure about pyepics and could not help much.
 
I use [CaChannel](https://github.com/CaChannel/CaChannel). It has also a  [``camonitor``](https://cachannel.readthedocs.io/en/latest/cachannel.html#CaChannel.util.camonitor) utility. (Disclaimer: I am the maintainer of CaChannel module)

**Comment by piuupiuupiuu** [comment]
Thanks for your help, I use CaChannel now and it works flawlessly!
