### ISSUE TITLE
driver.setParamValue does not work properly for numpy.ndarray values in Python3.6.1

### ISSUE THREAD

**Issue by fernandohds564** [paulscherrerinstitute/pcaspy#44]
In python3.6 the command
```
import numpy as np
a = np.array([1,2,3])
str(type(a))
```
returns 
 `<class 'numpy.ndarray'>`
instead of
` <type 'numpy.ndarray'>`
as assumed by  the code.

The consequence is that in the case of a `numpy.ndarray` a copy is not created, which can break updates of this type of PVs, depending on specific implementation of the applications.
A possible solution is to substitute the line
`elif str(type(value)) == "<type 'numpy.ndarray'>":`
by 
`elif  'numpy.ndarray' in str(type(value)):`

Thank you,
Fernando.

**Comment by xiaoqiangwang** [comment]
Thanks for finding the bug. I committed your suggested change, c9504864f9cbf433cc668e674e28e2b52c9f615e

**Comment by fernandohds564** [comment]
Thank you for fixing the problem so quickly.
