### ISSUE TITLE
Support for ADEL / MDEL

### ISSUE THREAD

**Issue by pklaus** [paulscherrerinstitute/pcaspy#46]
Hello @xiaoqiangwang & PSI, thanks for creating and maintaining this fine piece of software!

I would like to ask, if it's considered to implement the following or how difficult it would be to do so:

Support the fields `ADEL` and `MDEL` (as for [ai records](https://wiki-ext.aps.anl.gov/epics/index.php/RRM_3-14_Analog_Input#Monitor_Parameters) for example). This would require a change in at least two locations of `driver.py`: [L171](https://github.com/paulscherrerinstitute/pcaspy/blob/master/pcaspy/driver.py#L171) and [L541](https://github.com/paulscherrerinstitute/pcaspy/blob/master/pcaspy/driver.py#L541). There, the flag `DBE_LOG` (or its alias `DBE_MONITOR`) should only be set if the change from the previous to the current (new) value exceeds `ADEL` value.

For old-school IOCs, this is done with [recGblCheckDeadband()](https://github.com/epics-base/epics-base/blob/3.15/src/ioc/db/recGbl.c#L280) for example for `ai` records [here](https://github.com/epics-base/epics-base/blob/3.15/src/std/rec/aiRecord.c#L461).

A quick workaround for me would be to override `SimplePV.updateValue()` and `Driver.setParamValue()`.

**Comment by xiaoqiangwang** [comment]
I have thought of this but wondered whether this has any use cases. I will have a look at this now.

**Comment by xiaoqiangwang** [comment]
I just added ADEL/MDEL support in commit b236f3b, and also refactored the value/alarm checking code quite a bit.

It does not break the example programs, but I stay cautious until it gets widely tested.

**Comment by pklaus** [comment]
Wow, this was well done. And fast! With my PCASpy-based IOC, those changes worked out-of-the box. 

Maybe, you should add `'mdel', 'adel'` to the info_keys list of [Driver.getParamInfo()](https://github.com/paulscherrerinstitute/pcaspy/blob/master/pcaspy/driver.py#L277), too.

The use case for me is clear: Reduce the amount of noise for operator interfaces and reduce the amount of noise recorded with our CS-Studio-based archiver (reducing required database disk space).

By the way: The IOC I implemented using PCASpy is to be found in [this Github Gist](https://gist.github.com/pklaus/d86d8a00a57017888699f2a4e2e32e28). It connects our Lufft Opus20 device to EPICS/CA. It is a networked (PoE), calibrated temperature/humidity measurement device in our clean room laboratory. More devices of our slow-control setup (= the Micro-Vertex Detector of the CBM experiment) might follow.

Thanks again for implementing this.

**Comment by xiaoqiangwang** [comment]
I added mdel/adel to the getParamInfo. Thanks for the suggest.

**Comment by pklaus** [comment]
Great. Did you, by chance, forget to push the commit with that change?

**Comment by xiaoqiangwang** [comment]
Ok. Now the change is pushed.

**Comment by xiaoqiangwang** [comment]
This change has been included into 0.7 release.
