### ISSUE TITLE
getParamInfo is not in the PyPi version?

### ISSUE THREAD

**Issue by mennodoor** [paulscherrerinstitute/pcaspy#47]
Hi,

am I right that the getParamInfo method of the Driver-class is not yet in the PyPi version of pcaspy? If so, when do you plan to update that?

Thanks and best regards
menno

**Comment by xiaoqiangwang** [comment]
Right. That is not released yet. I plan to do it this week.

**Comment by xiaoqiangwang** [comment]
0.7 has been tagged. PyPI packages are soon to be uploaded via travis CI.
