### ISSUE TITLE
Unable to successfully run dummy.py example

### ISSUE THREAD

**Issue by gohierf** [paulscherrerinstitute/pcaspy#51]
Hello,

I just installed pcaspy in a virtual environment using `pip install pcaspy`.

The installation went fine, yet when I try to test the module using dummy.py I can't access to the PV:
`python dummy.py` does not seem to have any trouble, yet `camonitor MTEST:RAND` returns `MTEST:RAND                     *** Not connected (PV not found)`.

My environment variables are :
EPICS_BASE=/opt/epics/bases/base-3.15.4
EPICS_HOST_ARCH=centos7-x86_64

Do you have any suggestion on what I could investigate to work out what's wrong ?

Thanks

**Comment by xiaoqiangwang** [comment]
Might be you have special environment variables to specify the CA hosts? Check the output of
`$ printenv | grep EPICS_CA
`

**Comment by gohierf** [comment]
Thanks for the tip.
I actually managed to make it work on my PC, by adding
```bash
export EPICS_CA_AUTO_ADDR_LIST=NO
export EPICS_CA_ADDR_LIST=127.0.0.1
# or export EPICS_CA_ADDR_LIST = <my_ip>
```
However I could still not access the PV from another computer.
Eventually I had to deactivate my firewall, and then I do not need to set these EPICS_CA variables to have access to the PV from my computer or another.
Hence the issue is from my firewall configuration not from your module.
Thanks again, great module.
