### ISSUE TITLE
Type Unsigned Integer

### ISSUE THREAD

**Issue by fernandohds564** [paulscherrerinstitute/pcaspy#53]
Hi, @xiaoqiangwang,

I need to simulate an IOC which provides a PV of type unsigned integer of 32 bits.
Would it be possible to create a new type in pcaspy database which corresponds this type?

Thank you!

**Comment by xiaoqiangwang** [comment]
Channel access has only signed integer data types. A workaround is give it double type with 0 precision.

**Comment by fernandohds564** [comment]
Thanks, @xiaoqiangwang!
