### ISSUE TITLE
Add field support

### ISSUE THREAD

**Issue by John-Holt-Tessella** [paulscherrerinstitute/pcaspy#55]
Some of the processes we support use the standard EPICs db field, e.g. PV.VAL. The only way in which I seem to be able to implement this in pcaspy is to create a new PV for each of the fields. At the moment I only need `.DESC` and `.VAL` but I can imagine in the future I might want '`.EGU`, `.STAT` and `.SERV`. Is there a better way of doing this?

**Comment by xiaoqiangwang** [comment]
As you said, any db fields like PVs need to be manually created. Currently that is the only way.

But if these information is only for read purpose, it is possible to serve these extra PVs implicitly. Their values are mostly present in the gddAppType_dbr_ctrl_xxx structure.

**Comment by John-Holt-Tessella** [comment]
OK thank you I will look at that.
