### ISSUE TITLE
How to solve the problem that it publishes an amount of PVs such as more than 2000 PVs by pcaspy?

### ISSUE THREAD

**Issue by lzxiaohu** [paulscherrerinstitute/pcaspy#58]
Hello, I am a new learner in pcaspy. I try to publish more than 2000 PVs in one python program by pcaspy. However, when the program runs, it would produce the error: CAC: UDP recv error was "WINSOCK Error 10052. So I ask for help. Please help me.
![default](https://user-images.githubusercontent.com/20835667/47974851-6d8f2e00-e0e6-11e8-834f-990f7c9c4f97.PNG)
when the same program runs in the other computer, it generates errors:
![default](https://user-images.githubusercontent.com/20835667/47992039-d26a7880-e126-11e8-8898-738c4564c308.PNG)
At last, I put it running in the third computer, it runs normally.

**Comment by xiaoqiangwang** [comment]
I have used the following program to create 2000 dummy PVs, and seeing no problem. How is your program look like?

> caget MTEST:RAND1999
MTEST:RAND1999                 0

```
#!/usr/bin/env python

from pcaspy import Driver, SimpleServer

prefix = 'MTEST:'

class myDriver(Driver):
    def  __init__(self):
        super(myDriver, self).__init__()

if __name__ == '__main__':
    server = SimpleServer()
    pvdb = {}
    for i in range(2000):
        pvdb['RAND%d'%i] = {}
    server.createPV(prefix, pvdb)
    driver = myDriver()

    # process CA transactions
    while True:
        server.process(0.1)
```

**Comment by xiaoqiangwang** [comment]
The problem is that all PVs are using `'scan': 1`. Because the scan thread is individual to each PV, this requires 2000 threads, which might exceed the system limits.(I don't have the exact number though.)

It is suggested to use your own updating thread to update PV values in batch. See the tutorial https://pcaspy.readthedocs.io/en/latest/tutorial.html#scan-periodically, and the final remark.

**Comment by lzxiaohu** [comment]
I got it. However, I don't how to update PV values in batch. Now I am sure that PV values continue to changing through caget, while the command camonitor cannot monitor the changes of PV values. Can you explain in detail that how to update PV values in batch. Thanks!

**Comment by xiaoqiangwang** [comment]
At the end of calling `self.setParam`, add a call to `updatePVs`. e.g.
```
    # set PVs new values
    self.setParam('RAND1', 0.1)
    self.setParam('RAND2', 0.2)
    ...
    # update PVs new values to registered clients
    self.updatePVs()
```

**Comment by lzxiaohu** [comment]
Thank you for you precious advice. According to your suggestion, I have solved my problem.
