### ISSUE TITLE
problem with

### ISSUE THREAD

**Issue by vstadnytskyi** [paulscherrerinstitute/pcaspy#63]
I have followed the installation [instruction](https://pcaspy.readthedocs.io/en/latest/installation.html#installation-label) and [tutorial](https://pcaspy.readthedocs.io/en/latest/tutorial.html#example-1-expose-some-random-number-s) 

I am getting the following error

`libc++abi.dylib: terminating with uncaught exception of type epicsMutex::invalidMutex: epicsMutex::invalidMutex()`

Snippet of the code

```
n [14]: from pcaspy import SimpleServer, Driver

In [15]: server = SimpleServer()
libc++abi.dylib: terminating with uncaught exception of type epicsMutex::invalidMutex: epicsMutex::invalidMutex()
Abort trap: 6

```

I don't know what to make of it.

OS: Mac Mojave
Python: '2.7.15 (v2.7.15:ca079a3ea3, Apr 29 2018, 20:59:26) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]'

**Comment by xiaoqiangwang** [comment]
Can you add information about your operating system and Python version?

**Comment by vstadnytskyi** [comment]
@xiaoqiangwang 
> Can you add information about your operating system and Python version?

OS: Mac Mojave
Python: '2.7.15 (v2.7.15:ca079a3ea3, Apr 29 2018, 20:59:26) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]'

**Comment by xiaoqiangwang** [comment]
I suppose you were installing the binary wheel package. These packages were compiled to link libstdc++, which might have incompatible changes in Mojave. This is only my speculation and I have no Mojave system to verify.

I suggest you install pcaspy from source.
