### ISSUE TITLE
No Windows binaries available from PyPI repositories

### ISSUE THREAD

**Issue by alphanoob1337** [paulscherrerinstitute/pcaspy#70]
I tried to install PCASpy on Windows by first installing the EPICS Windows Tools 1.44 and SWIG. Then I used

`pip install pcaspy`.

It tries to compile pcaspy from source then, which first fails because it does not find the `EPICS_BASE` environment variable:

`OSError: Please define/validate EPICS_BASE environment variable`

After downloading the [EPICS base sources](https://epics.anl.gov/download/base/index.php) version R3.14.12.4 and setting the `EPICS_BASE` variable, `pip install` fails because it is unable to find `epicsVersion.h`. I looked for that file manually and it is not included in the EPICS base sources. Is this file only created while compiling EPICS or is that only available in other versions?

In the end I uninstalled Python 3.9 and reverted to Python 3.8 because then `pip install pcaspy` uses binaries provided by PyPI which work like a charm. Can you please provide Windows binaries for pcaspy in Python 3.9?

**Comment by xiaoqiangwang** [comment]
You may try a recent version of EPICS base, like R3.14.12.8.

In the mean time, I uploaded a Python 3.9 Windows wheel. You may try that out. The reason for not providing Python 3.9 wheels yet is that the building/packaging process is all automatised using conda distribution. And Python 3.9, released just one month ago, is not yet supported in conda.

**Comment by alphanoob1337** [comment]
As a side note: I very strongly prefer not to use Anaconda where possible. I had so many problems with it and I rarely need an Anaconda specific feature that would justify the effort of dealing with this extra layer of complexity. I agree that there are use cases where it makes a lot of sense to use Anaconda but for me this is very rarely the case.

So I very much appreciate that PCASpy can also be used without Anaconda. Thank you so much! The wheel you provided just 
installed without any problems.
