### ISSUE TITLE
pysh.py example in the tutorial does not work (caput'ed value is garbage).

### ISSUE THREAD

**Issue by CarlosCumming** [paulscherrerinstitute/pcaspy#73]
The pysh.py example in the pcaspy tutorial fails on both of my Linux machines (Ubuntu, centos7) using both python2 and python3, and epics 3.15.9. The following code produces this output with a "caput MTEST:COMMAND date":

$ ./pysh.py
('WRITE', 'COMMAND', '**_\xda_**')

This code is from the example stripped down to it's bare minimum, including removing the async example code.

```
#!/usr/bin/env python

import time
import sys
from pcaspy import Driver, SimpleServer

prefix = 'MTEST:'
pvdb = {
    'COMMAND' : {
        'type' : 'char',
        'count': 128,
    },
}

import math
class myDriver(Driver):
    def __init__(self):
        Driver.__init__(self)
        self.tid = None

    def write(self, reason, value):
        print("WRITE", reason, value)
        self.setParam(reason, value)
        return True

if __name__ == '__main__':
    server = SimpleServer()
    server.createPV(prefix, pvdb)
    driver = myDriver()

    while True:
        # process CA transactions
        server.process(0.1)
```

**Comment by xiaoqiangwang** [comment]
For PVs of char array, use the _-S_ switch of caget/caput command.
```
$ caput -S MTEST:COMMAND "a long command to run"
Old : MTEST:COMMAND 
New : MTEST:COMMAND a long command to run
```

**Comment by CarlosCumming** [comment]
Thanks! That worked!

However, I've used epics, including caput for over a decade, including
caput'ing strings (but never obviously, pcasspy). I've never had to use the
-S switch, and the example is still wrong.... as the caput in the example
also doesn't use -S.

I'm curious why it's needed in this instance???

thx, tom.c

**Comment by xiaoqiangwang** [comment]
For _string_ type, channel access limits the string length to 40. They are reported as _DBF_STRING_ by cainfo command. In EPICS IOC database, they can be the VAL field of stringin/stringout records, or DESC, INP, OUT fields to name a few. In pcaspy program, they are PVs configured as {"type": "string"}.

To work with long strings, use char arrays. They are reported as _DBF_CHAR_ with the _count_ as the string length. In EPICS IOC database, they are mostly configured as _waveform_ records with _FTVL=CHAR_ and _NELM=\<length\>_. Also adding a _$_ suffix to the _DBF_STRING_ type will also retrieve as char arrays. In pcaspy program, they are PVs configured as {"type": "char", "count": _\<length\>_}.

E.g.  this is a char array record in EPICS IOC,
```
record(waveform, "MTEST:COMMAND")
{
    field (FTVL, "CHAR")
    field (NELM, "128")
}
```

Here shows how _-S_ switch treats it as a string.
```
$ cainfo MTEST:COMMAND
MTEST:COMMAND
...
    Native data type: DBF_CHAR
    Request type:     DBR_CHAR
    Element count:    128

$ caget MTEST:COMMAND
MTEST:COMMAND 128 100 97 116 101 116 105 109 101 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...

$ caget -S MTEST:COMMAND
MTEST:COMMAND datetime

```
