### ISSUE TITLE
Unit vs Units in PV property

### ISSUE THREAD

**Issue by vstadnytskyi-FDA** [paulscherrerinstitute/pcaspy#80]
Hi All,

It seems that you are using keyword "unit"  when it comes to define units of a PV. I suspect that is a keyword that defines 'Engineering **Units**'. For example, PyEpics uses 'units' instead of unit.

Would be better to be consistent across different platforms? What are your thought?

**Comment by xiaoqiangwang** [comment]
If I recall correctly, my thought was that "this field defines the *unit* of this PV". Anyway renaming it to "units" is too late, making an alias is always possible. But I don't see that creates much clarity.
