### ISSUE TITLE
Discussion: strategies to update PVs, if a device collects a single data point at high repetition rate.

### ISSUE THREAD

**Issue by vstadnytskyi-FDA** [paulscherrerinstitute/pcaspy#84]
Hi,

I wanted to learn more about what are normal practices to deal with devices that collect data at, for example, 400Hz. I have a daq that spits out one float64 number at 400Hz. I can update PV every time I get a new value from the DAQ, or I can include some averaging capabilities if needed. Would it be more elegant to send, for example, 1 second worth of data as one PV. What are your thoughts?

**Comment by xiaoqiangwang** [comment]
The choices you give are all valid options. To summarise,
1. raw data input
2. N sample average
3. circular buffer
See the [compress record ](https://epics.anl.gov/base/R7-0/6-docs/compressRecord.html) for more algorithms.

Wether to implement them depends on your requirements.
