### ISSUE TITLE
Setting subfields over channel access

### ISSUE THREAD

**Issue by bsobhani** [paulscherrerinstitute/pcaspy#89]
If I try to do "caput pvname.hihi 12.34" I get a channel connect time out error, same with "caput pvname.HIHI 12.34". Is there a way to set the hihi/high/low/lolo limits from channel access? My ultimate goal is for the hihi limit to be configurable from CSS.

**Comment by xiaoqiangwang** [comment]
It is not the same as the IOC database, you would have to create these subfields in your program. Maybe someone has done similar things.
