### ISSUE TITLE
conda-forge stuck at 0.7.3 -> not usable with Python 3.10 or higher

### ISSUE THREAD

**Issue by spreiter** [paulscherrerinstitute/pcaspy#98]
The current version 0.8 released in March 2023 is not yet available via conda-forge. Since 0.7.3 still uses `collections.Iterable`, this version can not be used with Python >= 3.10 (see #76)

I found the repo, which seems to handle it [1], but since I am not aware of all changes, I would rather not take any step there.

Can this be updated?

[1] https://github.com/conda-forge/pcaspy-feedstock

**Comment by xiaoqiangwang** [comment]
0.8.0 introduced a serious issue, which has just got fixed. https://github.com/paulscherrerinstitute/pcaspy/issues/95.
The CI workflow keeps failing and I have't got time to investigate.

I am not responsible for pcaspy-feedstock and upgrade request has to be raised there. However I keep built conda packages here https://anaconda.org/paulscherrerinstitute/pcaspy if it helps.

**Comment by spreiter** [comment]
I see. I was not aware that there is a separate profile for conda packages. Thanks for pointing that out.
I will create a ticket at feedstock, maybe this can be updated as well.

I guess 0.8.1 will be release soon to fix the bug?

**Comment by xiaoqiangwang** [comment]
As soon as I get the github workflow working again, I will make a new release.

**Comment by xiaoqiangwang** [comment]
FYI: 0.8.1 is released.
